name: Get Team Members5

on:
  push:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  get-team-members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get team members
        id: get-team-members
        uses: montudor/github-team-members@v1.0.1
        with:
          org: lifinance
          team_slug: diamondpauser
          github_token: ${{ secrets.GIT_TOKEN }}

      - name: Print team members
        run: |
          echo "Team Members: ${{ steps.get-team-members.outputs.members }}"
