name: GetTeamMembers4

on:
  push:
  workflow_dispatch:

jobs:
  check-member:
    runs-on: ubuntu-latest
    name: Check if an user exists
    steps:
      - name: Check if member exists
        id: check-member-4
        uses: bryantson/check-member-exists-in-team-actions@1.0
        with:
          team_slug: diamondpauser
          org_slug: lifinance
          gh_token: ${{ github.token }}
          username: ${{ github.actor }}

      - name: Print whether member exists
        run: |
          echo "Does member exist: ${{ steps.check-member.outputs.exists-in-team }}"
