name: Get Team Members 3

on:
  push:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  get-team-members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get team members
        id: get-user-teams
        uses: tspascoal/get-user-teams-membership@v3
        with:
          username: ${{ github.actor }}
          organization: lifinance
          team: diamondpauser
          GITHUB_TOKEN: ${{ github.token }}

      - name: Print team members
        run: |
          echo "Teams: ${{ steps.get-user-teams.outputs.teams }}"
          echo "Is Team Member: ${{ steps.get-user-teams.outputs.isTeamMember }}"
